/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peluqueriacaninairene;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author irene
 */
public class PeluCanina extends javax.swing.JFrame {

    /**
     * Creates new form PeluCanina
     */
    private static Connection con;
    ResultSet rs;
    
    public VentanaVerDatos nuevaVentanaVerDatos;
    public VentanaInsertar nuevaVentanaInsertar;
    public VentanaEliminar nueVentanaEliminar;
    public VentanaLogsPedidos nuevaVentanaLogsPedidos;
    public VentanaModificar nuevaVentanaModificar;
    public VentanaLogsNotas nuevaVentanaLogsNotas;
    public VentanaConsultaRegalos nuevaVentanaConsultaRegalos;
    
    
    
    public PeluCanina() {
        setLocation (400, 200);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        conexionAbierta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        botonVerRegalos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        barraMenu = new javax.swing.JMenu();
        verDatos = new javax.swing.JMenuItem();
        insertarDatos = new javax.swing.JMenuItem();
        editarDatos = new javax.swing.JMenuItem();
        eliminarDatos = new javax.swing.JMenuItem();
        logs = new javax.swing.JMenu();
        logsPedidos = new javax.swing.JMenuItem();
        logsNotas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peluquería canina Baguira");

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel1.setText("Bienvenido al sistema de gestión de peluquería canina");

        jLabel2.setText("Un proyecto Java de Irene Díaz-Roncero Fraile");

        botonCerrar.setText("SALIR");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        botonVerRegalos.setText("Ver clientes con derecho a regalo");
        botonVerRegalos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerRegalosActionPerformed(evt);
            }
        });

        jMenuBar1.setName("Peluquería Canina Baguira"); // NOI18N

        barraMenu.setText("Menú");

        verDatos.setText("Ver datos");
        verDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDatosActionPerformed(evt);
            }
        });
        barraMenu.add(verDatos);

        insertarDatos.setText("Insertar");
        insertarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarDatosActionPerformed(evt);
            }
        });
        barraMenu.add(insertarDatos);

        editarDatos.setText("Editar");
        editarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDatosActionPerformed(evt);
            }
        });
        barraMenu.add(editarDatos);

        eliminarDatos.setText("Eliminar");
        eliminarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDatosActionPerformed(evt);
            }
        });
        barraMenu.add(eliminarDatos);

        logs.setText("Recordatorios");
        logs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsActionPerformed(evt);
            }
        });

        logsPedidos.setText("Pedidos");
        logsPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsPedidosActionPerformed(evt);
            }
        });
        logs.add(logsPedidos);

        logsNotas.setText("Notas");
        logsNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsNotasActionPerformed(evt);
            }
        });
        logs.add(logsNotas);

        barraMenu.add(logs);

        jMenuBar1.add(barraMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(botonVerRegalos, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(botonVerRegalos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDatosActionPerformed
        nuevaVentanaVerDatos=new VentanaVerDatos();
    }//GEN-LAST:event_verDatosActionPerformed

    private void insertarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarDatosActionPerformed
        nuevaVentanaInsertar=new VentanaInsertar();
    }//GEN-LAST:event_insertarDatosActionPerformed

    private void eliminarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDatosActionPerformed
        nueVentanaEliminar=new VentanaEliminar();
    }//GEN-LAST:event_eliminarDatosActionPerformed

    private void logsNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsNotasActionPerformed
        nuevaVentanaLogsNotas=new VentanaLogsNotas();
    }//GEN-LAST:event_logsNotasActionPerformed

    private void editarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDatosActionPerformed
        nuevaVentanaModificar=new VentanaModificar();
    }//GEN-LAST:event_editarDatosActionPerformed

    private void logsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsActionPerformed

    }//GEN-LAST:event_logsActionPerformed

    private void logsPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsPedidosActionPerformed
        nuevaVentanaLogsPedidos=new VentanaLogsPedidos();
    }//GEN-LAST:event_logsPedidosActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonVerRegalosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerRegalosActionPerformed
        nuevaVentanaConsultaRegalos=new VentanaConsultaRegalos();
    }//GEN-LAST:event_botonVerRegalosActionPerformed

    /**
     * @param args the command line arguments
     */
    private void conexionAbierta(){
        try {
            
            con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_final_irene?&user=root&password=papalumala31"
                           + "&useLegacyDatetimeCode=false&serverTimezone=UTC");        
            
            JOptionPane.showMessageDialog(null, "Conexión abierta con éxito", "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);
 		
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error", "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeluCanina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu barraMenu;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonVerRegalos;
    private javax.swing.JMenuItem editarDatos;
    private javax.swing.JMenuItem eliminarDatos;
    private javax.swing.JMenuItem insertarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu logs;
    private javax.swing.JMenuItem logsNotas;
    private javax.swing.JMenuItem logsPedidos;
    private javax.swing.JMenuItem verDatos;
    // End of variables declaration//GEN-END:variables
}
