/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peluqueriacaninairene;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author irene
 */
public class VentanaEliminar extends javax.swing.JFrame {
    ResultSet rs;
    /**
     * Creates new form VentanaEliminar
     */
    public VentanaEliminar() {
        setLocation (400, 300);
        setVisible(true);
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intro = new javax.swing.JLabel();
        advertencia = new javax.swing.JLabel();
        idCliente = new javax.swing.JLabel();
        nombreMascotaEliminar = new javax.swing.JTextField();
        botonBorrarCliente = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELIMINAR CLIENTE");

        intro.setText("Introduzca el nombre de la mascota del cliente del que desee eliminar la información.");

        advertencia.setForeground(new java.awt.Color(255, 0, 0));
        advertencia.setText("La información borrada no podrá ser recuperada.");

        idCliente.setText("Nombre de la mascota:");

        nombreMascotaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMascotaEliminarActionPerformed(evt);
            }
        });

        botonBorrarCliente.setText("BORRAR CLIENTE");
        botonBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarClienteActionPerformed(evt);
            }
        });

        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(intro, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(advertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(nombreMascotaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(botonBorrarCliente)
                        .addGap(31, 31, 31)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(intro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advertencia)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCliente)
                    .addComponent(nombreMascotaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrarCliente)
                    .addComponent(botonSalir))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void nombreMascotaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMascotaEliminarActionPerformed
        
    }//GEN-LAST:event_nombreMascotaEliminarActionPerformed

    private void botonBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarClienteActionPerformed
        eliminarCliente();
        resetTextField();
    }//GEN-LAST:event_botonBorrarClienteActionPerformed

    
    public void eliminarCliente(){
       Connection con;
       Statement st;
       Statement sta;
       try  {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_final_irene?&user=root&password=papalumala31"
                           + "&useLegacyDatetimeCode=false&serverTimezone=UTC");  
            
            String sql = "DELETE FROM datosclientes WHERE nombreMascota= '"+nombreMascotaEliminar.getText()+"'";
            st = con.createStatement();
            st.execute(sql);
            
            String sq = "DELETE FROM razasperros WHERE nombreMascota= '"+nombreMascotaEliminar.getText()+"'";
            sta = con.createStatement();
            st.execute(sq);
            
            JOptionPane.showMessageDialog(null, "Se eliminó el dueño y la mascota asociada.","WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);
            
	    } catch(Exception e){
		JOptionPane.showMessageDialog(null, "ERROR:"+e.toString(), "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);	
            }
    }
    
    public void resetTextField(){
        nombreMascotaEliminar.setText("");
    }
    
    
    public static void main(String args[]) {
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advertencia;
    private javax.swing.JButton botonBorrarCliente;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel idCliente;
    private javax.swing.JLabel intro;
    private javax.swing.JTextField nombreMascotaEliminar;
    // End of variables declaration//GEN-END:variables
}
