/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peluqueriacaninairene;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author irene
 */
public class VentanaConsultaRegalos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsultaRegalos
     */
    Connection con;
    ResultSet rs;
    
    public VentanaConsultaRegalos() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        introUno = new javax.swing.JLabel();
        introDos = new javax.swing.JLabel();
        heGastado = new javax.swing.JLabel();
        importeGastado = new javax.swing.JTextField();
        euros = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonVerRegalo = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        mostrarRegalo = new javax.swing.JLabel();
        etiquetaPienso = new javax.swing.JLabel();
        etiquetaPienso2 = new javax.swing.JLabel();
        botonVerPiensos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        etiquetaNombreMas = new javax.swing.JLabel();
        campoNombreMascota = new javax.swing.JTextField();
        etiquetaTuRaza = new javax.swing.JLabel();
        etiquetaTuPienso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGALOS");

        introUno.setText("En BAGUIRA tenemos regalos para nuestros clientes más fieles.");

        introDos.setForeground(new java.awt.Color(255, 0, 0));
        introDos.setText("Introduce el importe gastado en tienda y...¡descubre tu regalo!");

        heGastado.setText("He gastado:");

        importeGastado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importeGastadoActionPerformed(evt);
            }
        });

        euros.setText("€");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Tu regalo es:");

        botonVerRegalo.setText("VER REGALO");
        botonVerRegalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerRegaloActionPerformed(evt);
            }
        });

        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        mostrarRegalo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mostrarRegalo.setForeground(new java.awt.Color(0, 0, 204));

        etiquetaPienso.setText("¿Te han tocado un pienso o unas chuches de regalo?");

        etiquetaPienso2.setText("Descubre aquí cuál creemos que son los adecuados para tu perro:");

        botonVerPiensos.setText("VER PIENSOS");
        botonVerPiensos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerPiensosActionPerformed(evt);
            }
        });

        etiquetaNombreMas.setText("Nombre de mi mascota:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(botonVerPiensos, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonSalir))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaPienso2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(mostrarRegalo, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(introUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(introDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiquetaPienso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jSeparator1)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(heGastado, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(importeGastado, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(euros, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)
                                                .addComponent(botonVerRegalo)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaNombreMas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(campoNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(etiquetaTuRaza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etiquetaTuPienso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(introUno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(introDos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heGastado)
                    .addComponent(importeGastado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(euros)
                    .addComponent(botonVerRegalo))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarRegalo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaPienso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaPienso2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombreMas)
                    .addComponent(campoNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(etiquetaTuRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(etiquetaTuPienso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerPiensos)
                    .addComponent(botonSalir))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void importeGastadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importeGastadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_importeGastadoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonVerRegaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerRegaloActionPerformed
        calcularRegalo();
        resetTextField();
    }//GEN-LAST:event_botonVerRegaloActionPerformed

    private void botonVerPiensosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerPiensosActionPerformed
        buscarPiensoAdecuado();
    }//GEN-LAST:event_botonVerPiensosActionPerformed

    public void calcularRegalo(){
        String importe=importeGastado.getText();
        double impo=Double.valueOf(importe);
        
        if (impo>=50) {
            
            if (impo>=50 && impo<100) {
                mostrarRegalo.setText("Una bolsa de chuches para tu perro.");
            }
            if (impo>=100 && impo<150) {
                mostrarRegalo.setText("Una bolsa de pienso premium");
            }
            if (impo>=150 && impo<200) {
                mostrarRegalo.setText("Un baño y corte de pelo y de uñas para tu perro.");
            }
            if (impo>=200) {
                mostrarRegalo.setText("Tres bolsas de pienso premium y un baño gratis.");
            }
        } else {
                mostrarRegalo.setText(":( No llegas al importe mínimo para regalo.");
        }
        
    }
    
    
    public void resetTextField(){
        importeGastado.setText("");
    }
    
    
    public void buscarPiensoAdecuado(){
        try {
            
            con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_final_irene?&user=root&password=papalumala31"
                           + "&useLegacyDatetimeCode=false&serverTimezone=UTC");  
            
            String sql= "SELECT raza, piensoAdecuado FROM razasperros WHERE nombreMascota='"+campoNombreMascota.getText()+"'";
            
            Statement stmt = (Statement) con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY); 
            rs = stmt.executeQuery(sql);
            
            while (rs.next()){
                etiquetaTuRaza.setText("La raza de tu perro es "+rs.getString("raza")+".");
                etiquetaTuPienso.setText("El tipo de alimento más adecuado es "+rs.getString("piensoAdecuado")+".");
            }
 		
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "No tenemos registrado el nombre de su mascota. Compruebe la ortografía.", "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
    }
    
    
    
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsultaRegalos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVerPiensos;
    private javax.swing.JButton botonVerRegalo;
    private javax.swing.JTextField campoNombreMascota;
    private javax.swing.JLabel etiquetaNombreMas;
    private javax.swing.JLabel etiquetaPienso;
    private javax.swing.JLabel etiquetaPienso2;
    private javax.swing.JLabel etiquetaTuPienso;
    private javax.swing.JLabel etiquetaTuRaza;
    private javax.swing.JLabel euros;
    private javax.swing.JLabel heGastado;
    private javax.swing.JTextField importeGastado;
    private javax.swing.JLabel introDos;
    private javax.swing.JLabel introUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mostrarRegalo;
    // End of variables declaration//GEN-END:variables
}
