/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peluqueriacaninairene;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author irene
 */
public class VentanaLogsNotas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogsAciertos
     */
    public VentanaLogsNotas() {
        setLocation (400, 300);
        setVisible(true);
        initComponents();
        populateTextField();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        panelTextoNotas = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        tituloNotas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NOTAS");

        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setText("SALIR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        panelTextoNotas.setViewportView(areaTexto);

        tituloNotas.setText("Tareas pendientes y notas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(aceptar)
                        .addGap(18, 18, 18)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTextoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tituloNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTextoNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        escribirFichero();
    }//GEN-LAST:event_aceptarActionPerformed


  
    
    public void populateTextField(){
        File archivo = null;
        FileReader reader = null;
        BufferedReader buffer = null;
            try {
                archivo = new File("C:\\proyectoirene\\logsNotas.txt");
                reader = new FileReader (archivo);
                buffer = new BufferedReader(reader);
                String linea;
                    while( (linea=buffer.readLine()) != null) {
                        areaTexto.setText(linea);
                    }
                
                }
            catch(IOException e){
                e.printStackTrace();
            }finally{
                try{
                    if( null != reader ){
                        reader.close();
                    }
                }catch (IOException e2){
                    e2.printStackTrace();
                }
            }
    }
    
    public void escribirFichero(){
        //para leer 
        File archivo = null;
        FileReader rea = null;
        BufferedReader buf = null;
        //escribir
        FileWriter arch = null;
        PrintWriter pw = null;
        
        try {
            //leer lo que se ha escrito ahora: leerá lo que ya estaba y lo añadido
            archivo = new File("C:\\proyectoirene\\logsNotas.txt");
            rea = new FileReader (archivo);
            buf = new BufferedReader(rea);
            String linea;
            
            //escribir todo lo que se ha leído
            arch=new FileWriter("C:\\proyectoirene\\logsNotas.txt");
            pw=new PrintWriter(arch);
            
            pw.print(areaTexto.getText());
            
            pw.close();
        } catch (IOException e) {
        } finally {
            try {
           if (null != arch)
              arch.close();
           } catch (IOException e2) {
           }
        }
        JOptionPane.showMessageDialog(null, "Mensaje escrito con éxito.", "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);
    }
    
    public static void main(String args[]) {
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogsNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton cancelar;
    private javax.swing.JScrollPane panelTextoNotas;
    private javax.swing.JLabel tituloNotas;
    // End of variables declaration//GEN-END:variables
}
