/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peluqueriacaninairene;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author irene
 */
public class VentanaModificar extends javax.swing.JFrame {
    
    ResultSet rs;
    /**
     * Creates new form VentanaModificar
     */
    public VentanaModificar() {
        setLocation (400, 300);
        setVisible(true);
        initComponents();
        desplegablePeluqueros.addItem("Nerea");
        desplegablePeluqueros.addItem("José");
        desplegablePeluqueros.addItem("Ana");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        intro = new javax.swing.JLabel();
        advertencia = new javax.swing.JLabel();
        idCliente = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        dni = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        Ciudad = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        nombreMascota = new javax.swing.JLabel();
        idC = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        ape = new javax.swing.JTextField();
        dn = new javax.swing.JTextField();
        dir = new javax.swing.JTextField();
        ciu = new javax.swing.JTextField();
        tfno = new javax.swing.JTextField();
        nomMas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botonModificar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        desplegablePeluqueros = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MODIFICAR DATOS");

        intro.setText("Introduzca a continuación los nuevos datos del cliente a modificar.");

        advertencia.setForeground(new java.awt.Color(255, 0, 0));
        advertencia.setText("¡ATENCIÓN! El cliente debe haber sido previamente registrado en la base de datos.");

        idCliente.setText("ID cliente");

        nombre.setText("Nombre");

        apellidos.setText("Apellidos");

        dni.setText("DNI");

        direccion.setText("Dirección");

        Ciudad.setText("Ciudad");

        telefono.setText("Teléfono");

        nombreMascota.setText("Nombre Mascota");

        idC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCActionPerformed(evt);
            }
        });

        jLabel1.setText("Peluquero");

        botonModificar.setText("MODIFICAR");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(intro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(advertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botonModificar)
                            .addGap(38, 38, 38)
                            .addComponent(botonSalir))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                                .addComponent(desplegablePeluqueros, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idCliente)
                                    .addComponent(nombre)
                                    .addComponent(apellidos)
                                    .addComponent(dni)
                                    .addComponent(direccion)
                                    .addComponent(Ciudad)
                                    .addComponent(telefono)
                                    .addComponent(nombreMascota))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nom, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                    .addComponent(idC)
                                    .addComponent(ape)
                                    .addComponent(dn)
                                    .addComponent(dir)
                                    .addComponent(ciu)
                                    .addComponent(tfno)
                                    .addComponent(nomMas))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(intro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(advertencia)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCliente)
                    .addComponent(idC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos)
                    .addComponent(ape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni)
                    .addComponent(dn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(direccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ciudad)
                    .addComponent(ciu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(tfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreMascota)
                    .addComponent(nomMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(desplegablePeluqueros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonModificar)
                    .addComponent(botonSalir))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        modificarDatos();
        resetTextField();
    }//GEN-LAST:event_botonModificarActionPerformed

    private void idCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    public void modificarDatos(){
        Connection connection;
        PreparedStatement ps;
        try {
            
        connection =  DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_final_irene?&user=root&password=papalumala31"
                           + "&useLegacyDatetimeCode=false&serverTimezone=UTC");  
        ps=connection.prepareStatement("UPDATE datosclientes SET nombreDue=?, apellidos=?, dni=?, direccion=?, ciudad=?, telefono=?, nombreMascota=?, peluquero=? WHERE idCliente=?");
       
        int idCliente =Integer.parseInt(idC.getText());

        String peluqPreferido=(String) desplegablePeluqueros.getSelectedItem();
        
        ps.setString(1, nom.getText());
        ps.setString(2, ape.getText());
        ps.setString(3, dn.getText());
        ps.setString(4, dir.getText());
        ps.setString(5, ciu.getText());
        ps.setString(6, tfno.getText());
        ps.setString(7, nomMas.getText());
        ps.setString(8, peluqPreferido);
        ps.setInt(9, idCliente);
  
        ps.execute();
        
        JOptionPane.showMessageDialog(null, "Se modificó el registro correctamente.", "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);      
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: "+e.toString(), "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void resetTextField(){
        idC.setText("");
        nom.setText("");
        ape.setText("");
        dn.setText("");
        dir.setText("");
        ciu.setText("");
        tfno.setText("");
        nomMas.setText("");
    }
    
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel advertencia;
    private javax.swing.JTextField ape;
    private javax.swing.JLabel apellidos;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField ciu;
    private javax.swing.JComboBox<String> desplegablePeluqueros;
    private javax.swing.JTextField dir;
    private javax.swing.JLabel direccion;
    private javax.swing.JTextField dn;
    private javax.swing.JLabel dni;
    private javax.swing.JTextField idC;
    private javax.swing.JLabel idCliente;
    private javax.swing.JLabel intro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomMas;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombreMascota;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField tfno;
    // End of variables declaration//GEN-END:variables
}
