/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peluqueriacaninairene;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author irene
 */
public class VentanaInsertar extends javax.swing.JFrame {
    ResultSet rs;
    private String [] listaPeluqueros={"Nerea", "José", "Ana"};
    VentanaInsertarMascota nuevaVentanaInsertarMascota;
    
    /**
     * Creates new form VentanaInsertar
     */
    public VentanaInsertar() {
        setLocation (400, 300);
        setVisible(true);
        initComponents();
        desplegablePeluqueros.addItem("Nerea");
        desplegablePeluqueros.addItem("José");
        desplegablePeluqueros.addItem("Ana");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idCliente = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        dni = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        ciudad = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        nombreMascota = new javax.swing.JLabel();
        peluq = new javax.swing.JLabel();
        idC = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        ape = new javax.swing.JTextField();
        dn = new javax.swing.JTextField();
        dir = new javax.swing.JTextField();
        ciu = new javax.swing.JTextField();
        tfno = new javax.swing.JTextField();
        nomMas = new javax.swing.JTextField();
        desplegablePeluqueros = new javax.swing.JComboBox<>();
        botonInsertar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        botonVentanaMascota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRAR NUEVO CLIENTE");

        idCliente.setText("ID cliente");

        nombre.setText("Nombre");

        apellidos.setText("Apellidos");

        dni.setText("DNI");

        direccion.setText("Dirección");

        ciudad.setText("Ciudad");

        telefono.setText("Teléfono");

        nombreMascota.setText("Nombre mascota");

        peluq.setText("Peluquero");

        idC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCActionPerformed(evt);
            }
        });

        dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirActionPerformed(evt);
            }
        });

        ciu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciuActionPerformed(evt);
            }
        });

        nomMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomMasActionPerformed(evt);
            }
        });

        desplegablePeluqueros.setSelectedItem(null);
        desplegablePeluqueros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegablePeluquerosActionPerformed(evt);
            }
        });

        botonInsertar.setText("INSERTAR NUEVO CLIENTE");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        botonSalir.setText("SALIR");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        botonVentanaMascota.setText("REGISTRAR AQUÍ NUEVA MASCOTA");
        botonVentanaMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentanaMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVentanaMascota, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(direccion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dir, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ape, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(nom)
                                    .addComponent(idC)
                                    .addComponent(dn))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombreMascota)
                                            .addComponent(idCliente)
                                            .addComponent(ciudad)
                                            .addComponent(telefono)
                                            .addComponent(nombre)
                                            .addComponent(peluq))
                                        .addGap(27, 27, 27))
                                    .addComponent(dni))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(apellidos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botonSalir)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ciu)
                                    .addComponent(tfno)
                                    .addComponent(nomMas)
                                    .addComponent(desplegablePeluqueros, 0, 163, Short.MAX_VALUE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCliente)
                    .addComponent(idC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidos)
                    .addComponent(ape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni)
                    .addComponent(dn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion)
                    .addComponent(dir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudad)
                    .addComponent(ciu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefono)
                    .addComponent(tfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreMascota)
                    .addComponent(nomMas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peluq, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desplegablePeluqueros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(botonVentanaMascota)
                .addGap(18, 18, 18)
                .addComponent(botonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ciuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciuActionPerformed

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        insertarDatos();
        resetTextField();
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void idCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCActionPerformed

    private void dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dirActionPerformed

    private void nomMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomMasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomMasActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void desplegablePeluquerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegablePeluquerosActionPerformed
        
    }//GEN-LAST:event_desplegablePeluquerosActionPerformed

    private void botonVentanaMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentanaMascotaActionPerformed
        nuevaVentanaInsertarMascota=new VentanaInsertarMascota();
    }//GEN-LAST:event_botonVentanaMascotaActionPerformed
    
    public void insertarDatos(){
        Connection connection;
        PreparedStatement ps;
        try {
            connection =  DriverManager.getConnection("jdbc:mysql://localhost:3306/proyecto_final_irene?&user=root&password=papalumala31"
                           + "&useLegacyDatetimeCode=false&serverTimezone=UTC");  
            ps=connection.prepareStatement("INSERT INTO datosclientes VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)");
       
            int idCliente =Integer.parseInt(idC.getText());
            String peluqPreferido=(String) desplegablePeluqueros.getSelectedItem();
        
            ps.setInt(1, idCliente);
            ps.setString(2, nom.getText());
            ps.setString(3, ape.getText());
            ps.setString(4, dn.getText());
            ps.setString(5, dir.getText());
            ps.setString(6, ciu.getText());
            ps.setString(7, tfno.getText());
            ps.setString(8, nomMas.getText());
            ps.setString(9, peluqPreferido);
            
  
            ps.executeUpdate();
            rs=null;
            JOptionPane.showMessageDialog(null, "Se insertó el registro correctamente. ¡No olvide también REGISTRAR A SU MASCOTA para que podamos ofercerle las mejores promociones!", "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);      
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: "+e.toString(), "WARNING MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    public void resetTextField(){
        idC.setText("");
        nom.setText("");
        ape.setText("");
        dn.setText("");
        dir.setText("");
        ciu.setText("");
        tfno.setText("");
        nomMas.setText("");
       
    }
    
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInsertar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ape;
    private javax.swing.JLabel apellidos;
    private javax.swing.JButton botonInsertar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVentanaMascota;
    private javax.swing.JTextField ciu;
    private javax.swing.JLabel ciudad;
    private javax.swing.JComboBox<String> desplegablePeluqueros;
    private javax.swing.JTextField dir;
    private javax.swing.JLabel direccion;
    private javax.swing.JTextField dn;
    private javax.swing.JLabel dni;
    private javax.swing.JTextField idC;
    private javax.swing.JLabel idCliente;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomMas;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombreMascota;
    private javax.swing.JLabel peluq;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField tfno;
    // End of variables declaration//GEN-END:variables
}
